export type Point = { name: string; lat: number; lon: number };

export type WebcamIframe = {
  kind: 'iframe';
  title: string;
  src: string;
  sourceHref: string;
  modal?: boolean;
};

export type WebcamLink = {
  kind: 'link';
  title: string;
  ctaTitle: string;
  ctaSubtitle: string;
  href: string;
  note?: string;
};

export type Webcam = WebcamIframe | WebcamLink;

export type EcccZone = { label: string; siteId: string; mapId: string };
export type DeepDiveLink = { label: string; href: string };

export type StationConfig = {
  slug: string;
  brand: {
    short: string;
    tagline: string;
    logoSrc?: string;              // falls back to /logo-rcmsar.png
    logoAlt?: string;              // falls back to "Royal Canadian Marine Search and Rescue"
    faviconSrc?: string;           // falls back to /favicon.png
    appleTouchIconSrc?: string;    // falls back to /apple-touch-icon.png
    accent: string;
    themeColor: string;
  };
  meta: {
    title: string;
    description: string;
    footerCredit: string;
  };
  labels: {
    windSub: string;
    seaSub: string;
    tideSub: string;
    tideCardHeading: string;
    sunFootnote: string;
    forecastLocation: string;
    marineWarningLocation: string;
  };
  tz: string;
  center: Point;
  tideStationId: string;
  points: Point[];
  marinePoint: Point;
  refreshMs: number;
  eccc: EcccZone[];
  windy: { lat: number; lon: number; zoom: number };
  webcams: Webcam[];
  deepDive: DeepDiveLink[];
  currents?: {
    show: boolean;
    center?: Point;
    zoom?: number;
  };
};

export const STATIONS = {
  sar33: {
    slug: 'sar33',
    brand: {
      short: 'RCMSAR 33 · Oak Bay',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar33/logo.png',
      logoAlt: 'RCMSAR 33 Oak Bay Sea Rescue Society',
      faviconSrc: '/stations/sar33/favicon.png',
      appleTouchIconSrc: '/stations/sar33/apple-touch-icon.png',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 33 Oak Bay — Local Conditions',
      description: 'RCMSAR Unit 33 Oak Bay local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 33 Oak Bay conditions',
    },
    labels: {
      windSub: 'Oak Bay',
      seaSub: 'Haro Strait',
      tideSub: 'Station 07130',
      tideCardHeading: 'Tide — Oak Bay (07130)',
      sunFootnote: 'Computed locally (SunCalc) for Oak Bay.',
      forecastLocation: 'Oak Bay',
      marineWarningLocation: 'Oak Bay',
    },
    tz: 'America/Vancouver',
    center: { name: 'Oak Bay', lat: 48.424, lon: -123.301 },
    tideStationId: '5cebf1df3d0f4a073c4bbd22',
    points: [
      { name: 'Willows Beach', lat: 48.4326, lon: -123.2958 },
      { name: 'Cattle Point',  lat: 48.4383, lon: -123.2920 },
      { name: 'Discovery Is.', lat: 48.4247, lon: -123.2261 },
      { name: 'Kelp Reef',     lat: 48.4573, lon: -123.2385 },
      { name: 'Gonzales Pt',   lat: 48.4123, lon: -123.2905 },
      { name: 'Harling Pt',    lat: 48.4098, lon: -123.2947 },
      { name: 'Trial Is.',     lat: 48.3939, lon: -123.3053 },
      { name: 'Victoria Hbr',  lat: 48.4235, lon: -123.3880 },
      { name: 'Dallas Rd',     lat: 48.4085, lon: -123.3520 },
    ],
    marinePoint: { name: 'Haro Strait', lat: 48.44, lon: -123.24 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Haro Strait', siteId: '06100', mapId: '02' },
      { label: 'Juan de Fuca Strait — east entrance', siteId: '07003', mapId: '02' },
    ],
    windy: { lat: 48.424, lon: -123.28, zoom: 11 },
    webcams: [
      {
        kind: 'iframe',
        title: 'Dallas Road webcam',
        src: 'https://mds.multivista.com/index.cfm?fuseaction=aPublicWebcam.embed&WebcamPublicEmbedUID=8E2F0FF9-3D83-4193-ABA5-3B90D4AC4006&HLS=1&width=1024&height=576&background=none',
        sourceHref: 'https://windisgood.com/dallas-road-webcam-live.html',
        modal: true,
      },
      {
        kind: 'link',
        title: 'Willows Beach webcam',
        ctaTitle: 'Open Willows Beach webcam',
        ctaSubtitle: 'Opens the WindIsGood webcam page ↗',
        href: 'https://windisgood.com/willows-beach.html',
        note: 'The direct image URL is blocked by the source site, so this opens the official webcam page instead.',
      },
      {
        kind: 'link',
        title: 'Ross Bay webcam',
        ctaTitle: 'Open Ross Bay webcam',
        ctaSubtitle: 'Video owner has disabled embedding ↗',
        href: 'https://windisgood.com/ross-bay-webcam-live.html',
        note: 'The YouTube video (via camstreamer) blocks external embeds, so this opens the source page instead.',
      },
    ],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'WindIsGood — Willows Beach ↗',     href: 'https://windisgood.com/willows-beach.html' },
      { label: 'WindIsGood — Dallas Road ↗',       href: 'https://windisgood.com/dallas-road.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?48.434,-123.169,11' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/en/city/ca/british-columbia/oak-bay/hourly' },
      { label: 'DFO tides — 07130 ↗',              href: 'https://www.tides.gc.ca/en/stations/07130' },
    ],
  } satisfies StationConfig,
  sar25: {
    slug: 'sar25',
    brand: {
      short: 'RCMSAR 25 · Salt Spring',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar25/logo.jpg',
      logoAlt: 'RCMSAR 25 Salt Spring Island',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 25 Salt Spring — Local Conditions',
      description: 'RCMSAR Unit 25 Salt Spring Island local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 25 Salt Spring conditions',
    },
    labels: {
      windSub: 'Vesuvius Bay',
      seaSub: 'Trincomali Ch.',
      tideSub: 'Crofton (07450)',
      tideCardHeading: 'Tide — Crofton (07450)',
      sunFootnote: 'Computed locally (SunCalc) for Vesuvius Bay.',
      forecastLocation: 'Vesuvius Bay',
      marineWarningLocation: 'Vesuvius Bay',
    },
    tz: 'America/Vancouver',
    center: { name: 'Vesuvius Bay', lat: 48.8833, lon: -123.5680 },
    tideStationId: '5cebf1e03d0f4a073c4bbd43',
    points: [
      { name: 'Vesuvius Bay', lat: 48.8833, lon: -123.5680 },
      { name: 'Booth Bay',    lat: 48.8880, lon: -123.5330 },
      { name: 'Ganges Hbr',   lat: 48.8580, lon: -123.4995 },
      { name: 'Long Hbr',     lat: 48.8500, lon: -123.4510 },
      { name: 'Fulford Hbr',  lat: 48.7660, lon: -123.4510 },
      { name: 'Beaver Pt',    lat: 48.7810, lon: -123.3720 },
      { name: 'Musgrave Ldg', lat: 48.7620, lon: -123.5770 },
      { name: 'Southey Pt',   lat: 48.9470, lon: -123.6180 },
      { name: 'Erskine Pt',   lat: 48.8220, lon: -123.6010 },
    ],
    marinePoint: { name: 'Trincomali Ch.', lat: 48.910, lon: -123.470 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
    ],
    windy: { lat: 48.83, lon: -123.53, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',       href: 'https://windisgood.com/island-map2.html' },
      { label: 'WindIsGood — Gulf Islands ↗',     href: 'https://windisgood.com/gulf-islands.html' },
      { label: 'WindIsGood — Ganges ↗',           href: 'https://windisgood.com/ganges.html' },
      { label: 'Windy.com full ↗',                href: 'https://www.windy.com/?48.83,-123.53,11' },
      { label: 'Weather Network — hourly ↗',      href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/ganges' },
      { label: 'DFO tides — Crofton 07450 ↗',     href: 'https://www.tides.gc.ca/en/stations/07450' },
      { label: 'DFO tides — Fulford Hbr 07330 ↗', href: 'https://www.tides.gc.ca/en/stations/07330' },
    ],
  } satisfies StationConfig,
  hq: {
    slug: 'hq',
    brand: {
      short: 'RCMSAR HQ · Pedder Bay',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/hq/logo.png',
      logoAlt: 'RCMSAR HQ Pedder Bay',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR HQ Pedder Bay — Local Conditions',
      description: 'RCMSAR HQ Pedder Bay local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR HQ Pedder Bay conditions',
    },
    labels: {
      windSub: 'Pedder Bay',
      seaSub: 'Juan de Fuca',
      tideSub: 'Station 07080',
      tideCardHeading: 'Tide — Pedder Bay (07080)',
      sunFootnote: 'Computed locally (SunCalc) for Pedder Bay.',
      forecastLocation: 'Pedder Bay',
      marineWarningLocation: 'Pedder Bay',
    },
    tz: 'America/Vancouver',
    center: { name: 'Pedder Bay Marina', lat: 48.3495, lon: -123.5511 },
    tideStationId: '5cebf1df3d0f4a073c4bbd15',
    points: [
      { name: 'Pedder Bay Marina', lat: 48.3495, lon: -123.5511 },
      { name: 'Race Rocks',        lat: 48.2979, lon: -123.5311 },
      { name: 'William Head',      lat: 48.3410, lon: -123.5369 },
      { name: 'Bentinck Is.',      lat: 48.3211, lon: -123.5461 },
      { name: 'Christopher Pt',    lat: 48.3212, lon: -123.5580 },
      { name: 'Whirl Bay',         lat: 48.3305, lon: -123.5670 },
      { name: 'Becher Bay',        lat: 48.3349, lon: -123.6038 },
      { name: 'Rocky Pt',          lat: 48.3193, lon: -123.5240 },
      { name: 'Albert Head',       lat: 48.3945, lon: -123.4815 },
      { name: 'Beechey Head',      lat: 48.3335, lon: -123.6486 },
    ],
    marinePoint: { name: 'Juan de Fuca (S of Race Rocks)', lat: 48.22, lon: -123.55 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Juan de Fuca Strait — east entrance',   siteId: '07003', mapId: '02' },
      { label: 'Juan de Fuca Strait — central strait',  siteId: '07010', mapId: '02' },
      { label: 'Haro Strait',                           siteId: '06100', mapId: '02' },
    ],
    windy: { lat: 48.31, lon: -123.55, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',              href: 'https://windisgood.com/island-map2.html' },
      { label: 'WindIsGood — Race Rocks ↗',              href: 'https://windisgood.com/race-rocks.html' },
      { label: 'WindIsGood — Sooke ↗',                   href: 'https://windisgood.com/sooke-webcam.html' },
      { label: 'WindIsGood — Dallas Road ↗',             href: 'https://windisgood.com/dallas-road.html' },
      { label: 'Windy.com full ↗',                       href: 'https://www.windy.com/?48.31,-123.55,11' },
      { label: 'Weather Network — Metchosin hourly ↗',   href: 'https://www.theweathernetwork.com/ca/hourly/bc/metchosin' },
      { label: 'DFO tides — 07080 Pedder Bay ↗',         href: 'https://www.tides.gc.ca/en/stations/07080' },
      { label: 'DFO currents — 07090 Race Passage ↗',    href: 'https://www.tides.gc.ca/en/stations/07090' },
    ],
  } satisfies StationConfig,
  sar01: {
    slug: 'sar01',
    brand: {
      short: 'RCMSAR 01 · West Vancouver',
      tagline: 'Local Marine Conditions',
      faviconSrc: '/stations/sar01/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 01 West Vancouver — Local Conditions',
      description: 'RCMSAR Unit 01 West Vancouver (Horseshoe Bay) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 01 West Vancouver conditions',
    },
    labels: {
      windSub: 'Horseshoe Bay',
      seaSub: 'Howe Sound',
      tideSub: 'Point Atkinson (07795)',
      tideCardHeading: 'Tide — Point Atkinson (07795)',
      sunFootnote: 'Computed locally (SunCalc) for Horseshoe Bay.',
      forecastLocation: 'Horseshoe Bay',
      marineWarningLocation: 'Howe Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Horseshoe Bay', lat: 49.3765, lon: -123.2735 },
    tideStationId: '5cebf1de3d0f4a073c4bb94c',
    points: [
      { name: 'Horseshoe Bay',  lat: 49.3765, lon: -123.2735 },
      { name: 'Whytecliff Pt',  lat: 49.3729, lon: -123.2870 },
      { name: 'Point Atkinson', lat: 49.3375, lon: -123.2536 },
      { name: 'Passage Is.',    lat: 49.3438, lon: -123.3103 },
      { name: 'Bowen Is. (Snug Cove)', lat: 49.3826, lon: -123.3300 },
      { name: 'Grebe Is.',      lat: 49.3612, lon: -123.2929 },
      { name: 'Copper Cove',    lat: 49.3680, lon: -123.2618 },
      { name: 'Fisherman\'s Cove', lat: 49.3549, lon: -123.2745 },
    ],
    marinePoint: { name: 'Howe Sound entrance', lat: 49.36, lon: -123.32 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Howe Sound',                                 siteId: '14400', mapId: '02' },
      { label: 'Strait of Georgia — south of Nanaimo',       siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 49.37, lon: -123.28, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?49.37,-123.28,11' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/west-vancouver' },
      { label: 'DFO tides — 07795 Point Atkinson ↗', href: 'https://www.tides.gc.ca/en/stations/07795' },
    ],
  } satisfies StationConfig,
  sar02: {
    slug: 'sar02',
    brand: {
      short: 'RCMSAR 02 · North Vancouver',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar02/logo.png',
      logoAlt: 'RCMSAR 02 North Vancouver',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 02 North Vancouver — Local Conditions',
      description: 'RCMSAR Unit 02 North Vancouver (Burrard Inlet, Indian Arm) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 02 North Vancouver conditions',
    },
    labels: {
      windSub: 'Burrard Inlet',
      seaSub: 'Burrard Inlet',
      tideSub: 'Vancouver (07735)',
      tideCardHeading: 'Tide — Vancouver (07735)',
      sunFootnote: 'Computed locally (SunCalc) for Burrard Inlet.',
      forecastLocation: 'North Vancouver',
      marineWarningLocation: 'Burrard Inlet',
    },
    tz: 'America/Vancouver',
    center: { name: 'Lynnwood Marina', lat: 49.3012, lon: -123.0250 },
    tideStationId: '5cebf1de3d0f4a073c4bb943',
    points: [
      { name: 'Lynnwood Marina', lat: 49.3012, lon: -123.0250 },
      { name: 'Second Narrows', lat: 49.2947, lon: -123.0245 },
      { name: 'Cates Park',     lat: 49.3014, lon: -122.9679 },
      { name: 'Deep Cove',      lat: 49.3268, lon: -122.9485 },
      { name: 'Belcarra',       lat: 49.3129, lon: -122.9291 },
      { name: 'Bedwell Bay',    lat: 49.3313, lon: -122.9179 },
      { name: 'Roche Pt',       lat: 49.2960, lon: -122.9880 },
      { name: 'Lions Gate',     lat: 49.3154, lon: -123.1387 },
      { name: 'Port Moody',     lat: 49.2877, lon: -122.8658 },
    ],
    marinePoint: { name: 'Burrard Inlet', lat: 49.30, lon: -123.05 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Howe Sound',                           siteId: '14400', mapId: '02' },
    ],
    windy: { lat: 49.30, lon: -123.03, zoom: 12 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?49.30,-123.03,12' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/north-vancouver' },
      { label: 'DFO tides — 07735 Vancouver ↗',    href: 'https://www.tides.gc.ca/en/stations/07735' },
      { label: 'DFO currents — 07745 Second Narrows ↗', href: 'https://www.tides.gc.ca/en/stations/07745' },
    ],
  } satisfies StationConfig,
  sar04: {
    slug: 'sar04',
    brand: {
      short: 'RCMSAR 04 · Squamish',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 04 Squamish — Local Conditions',
      description: 'RCMSAR Unit 04 Squamish (Howe Sound) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 04 Squamish conditions',
    },
    labels: {
      windSub: 'Squamish',
      seaSub: 'Howe Sound',
      tideSub: 'Squamish (07811)',
      tideCardHeading: 'Tide — Squamish (07811)',
      sunFootnote: 'Computed locally (SunCalc) for Squamish.',
      forecastLocation: 'Squamish',
      marineWarningLocation: 'Howe Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Squamish Terminal', lat: 49.7000, lon: -123.1550 },
    tideStationId: '5cebf1de3d0f4a073c4bb94e',
    points: [
      { name: 'Squamish Terminal', lat: 49.7000, lon: -123.1550 },
      { name: 'Darrell Bay',       lat: 49.6690, lon: -123.1690 },
      { name: 'Britannia Beach',   lat: 49.6216, lon: -123.2058 },
      { name: 'Porteau Cove',      lat: 49.5570, lon: -123.2354 },
      { name: 'Anvil Is.',         lat: 49.5745, lon: -123.3049 },
      { name: 'Woodfibre',         lat: 49.6704, lon: -123.2537 },
      { name: 'Watts Pt',          lat: 49.6280, lon: -123.2050 },
    ],
    marinePoint: { name: 'Howe Sound — Anvil Is.', lat: 49.55, lon: -123.30 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Howe Sound', siteId: '14400', mapId: '02' },
    ],
    windy: { lat: 49.65, lon: -123.20, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?49.65,-123.20,11' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/squamish' },
      { label: 'DFO tides — 07811 Squamish ↗',     href: 'https://www.tides.gc.ca/en/stations/07811' },
      { label: 'DFO tides — 07808 Darrell Bay ↗',  href: 'https://www.tides.gc.ca/en/stations/07808' },
    ],
  } satisfies StationConfig,
  sar05: {
    slug: 'sar05',
    brand: {
      short: 'RCMSAR 05 · Crescent Beach',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar05/logo.png',
      logoAlt: 'RCMSAR 05 Crescent Beach',
      faviconSrc: '/stations/sar05/favicon.png',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 05 Crescent Beach — Local Conditions',
      description: 'RCMSAR Unit 05 Crescent Beach (Boundary Bay, South Surrey) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 05 Crescent Beach conditions',
    },
    labels: {
      windSub: 'Crescent Beach',
      seaSub: 'Boundary Bay',
      tideSub: 'Crescent Beach (07579)',
      tideCardHeading: 'Tide — Crescent Beach (07579)',
      sunFootnote: 'Computed locally (SunCalc) for Crescent Beach.',
      forecastLocation: 'Crescent Beach',
      marineWarningLocation: 'Boundary Bay',
    },
    tz: 'America/Vancouver',
    center: { name: 'Crescent Beach Marina', lat: 49.0490, lon: -122.8810 },
    tideStationId: '5dd3064fe0fdc4b9b4be69d7',
    points: [
      { name: 'Crescent Beach', lat: 49.0490, lon: -122.8810 },
      { name: 'Blackie Spit',   lat: 49.0625, lon: -122.8779 },
      { name: 'White Rock Pier', lat: 49.0140, lon: -122.8144 },
      { name: 'Semiahmoo Bay',  lat: 49.0000, lon: -122.8500 },
      { name: 'Kwomais Pt',     lat: 49.0224, lon: -122.8843 },
      { name: 'Boundary Bay',   lat: 49.0250, lon: -122.9500 },
      { name: 'Point Roberts',  lat: 48.9820, lon: -123.0750 },
    ],
    marinePoint: { name: 'Boundary Bay', lat: 49.02, lon: -122.98 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
    ],
    windy: { lat: 49.03, lon: -122.92, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',          href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                   href: 'https://www.windy.com/?49.03,-122.92,11' },
      { label: 'Weather Network — hourly ↗',         href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/white-rock' },
      { label: 'DFO tides — 07579 Crescent Beach ↗', href: 'https://www.tides.gc.ca/en/stations/07579' },
      { label: 'DFO tides — 07577 White Rock ↗',     href: 'https://www.tides.gc.ca/en/stations/07577' },
    ],
  } satisfies StationConfig,
  sar08: {
    slug: 'sar08',
    brand: {
      short: 'RCMSAR 08 · Delta',
      tagline: 'Local Marine Conditions',
      faviconSrc: '/stations/sar08/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 08 Delta — Local Conditions',
      description: 'RCMSAR Unit 08 Delta (Point Roberts) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 08 Delta conditions',
    },
    labels: {
      windSub: 'Point Roberts',
      seaSub: 'Strait of Georgia',
      tideSub: 'Roberts Bank (07592)',
      tideCardHeading: 'Tide — Roberts Bank (07592)',
      sunFootnote: 'Computed locally (SunCalc) for Point Roberts.',
      forecastLocation: 'Point Roberts',
      marineWarningLocation: 'Strait of Georgia',
    },
    tz: 'America/Vancouver',
    center: { name: 'Point Roberts Marina', lat: 48.9820, lon: -123.0750 },
    tideStationId: '5cebf1e13d0f4a073c4bbf85',
    points: [
      { name: 'Point Roberts Marina', lat: 48.9820, lon: -123.0750 },
      { name: 'Lily Pt',        lat: 48.9741, lon: -123.0308 },
      { name: 'Point Roberts NW', lat: 49.0025, lon: -123.0910 },
      { name: 'Tsawwassen Ferry', lat: 49.0068, lon: -123.1293 },
      { name: 'Roberts Bank',   lat: 49.0150, lon: -123.1560 },
      { name: 'Boundary Bay',   lat: 49.0250, lon: -122.9500 },
      { name: 'Semiahmoo Bay',  lat: 49.0000, lon: -122.8500 },
    ],
    marinePoint: { name: 'Strait of Georgia — south', lat: 48.95, lon: -123.20 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
    ],
    windy: { lat: 48.98, lon: -123.08, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?48.98,-123.08,11' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/tsawwassen' },
      { label: 'DFO tides — 07592 Roberts Bank ↗', href: 'https://www.tides.gc.ca/en/stations/07592' },
      { label: 'DFO tides — 07590 Tsawwassen ↗',   href: 'https://www.tides.gc.ca/en/stations/07590' },
    ],
  } satisfies StationConfig,
  sar10: {
    slug: 'sar10',
    brand: {
      short: 'RCMSAR 10 · Richmond',
      tagline: 'Local Marine Conditions',
      faviconSrc: '/stations/sar10/favicon.gif',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 10 Richmond — Local Conditions',
      description: 'RCMSAR Unit 10 Richmond (Steveston & Middle Arm, Fraser River) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 10 Richmond conditions',
    },
    labels: {
      windSub: 'Steveston',
      seaSub: 'Strait of Georgia',
      tideSub: 'Steveston (07607)',
      tideCardHeading: 'Tide — Steveston (07607)',
      sunFootnote: 'Computed locally (SunCalc) for Steveston.',
      forecastLocation: 'Steveston',
      marineWarningLocation: 'Strait of Georgia',
    },
    tz: 'America/Vancouver',
    center: { name: 'Steveston', lat: 49.1245, lon: -123.1922 },
    tideStationId: '5cebf1e13d0f4a073c4bbf8c',
    points: [
      { name: 'Steveston',   lat: 49.1245, lon: -123.1922 },
      { name: 'Sand Heads',  lat: 49.1052, lon: -123.3042 },
      { name: 'Iona Jetty',  lat: 49.2160, lon: -123.2110 },
      { name: 'Middle Arm',  lat: 49.1780, lon: -123.1810 },
      { name: 'Roberts Bank', lat: 49.0150, lon: -123.1560 },
      { name: 'Sea Is. (YVR)', lat: 49.1935, lon: -123.1859 },
      { name: 'Point Grey',  lat: 49.2670, lon: -123.2620 },
    ],
    marinePoint: { name: 'Strait of Georgia — Sand Heads', lat: 49.10, lon: -123.35 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 49.12, lon: -123.20, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?49.12,-123.20,11' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/richmond' },
      { label: 'DFO tides — 07607 Steveston ↗',    href: 'https://www.tides.gc.ca/en/stations/07607' },
      { label: 'DFO tides — 07594 Sand Heads ↗',   href: 'https://www.tides.gc.ca/en/stations/07594' },
    ],
  } satisfies StationConfig,
  sar12: {
    slug: 'sar12',
    brand: {
      short: 'RCMSAR 12 · Halfmoon Bay',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar12/logo.png',
      logoAlt: 'RCMSAR 12 Halfmoon Bay',
      faviconSrc: '/stations/sar12/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 12 Halfmoon Bay — Local Conditions',
      description: 'RCMSAR Unit 12 Halfmoon Bay (Sunshine Coast) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 12 Halfmoon Bay conditions',
    },
    labels: {
      windSub: 'Halfmoon Bay',
      seaSub: 'Malaspina Strait',
      tideSub: 'Halfmoon Bay (07830)',
      tideCardHeading: 'Tide — Halfmoon Bay (07830)',
      sunFootnote: 'Computed locally (SunCalc) for Halfmoon Bay.',
      forecastLocation: 'Halfmoon Bay',
      marineWarningLocation: 'Strait of Georgia',
    },
    tz: 'America/Vancouver',
    center: { name: 'Halfmoon Bay', lat: 49.5110, lon: -123.9120 },
    tideStationId: '5cebf1de3d0f4a073c4bb952',
    points: [
      { name: 'Halfmoon Bay',   lat: 49.5110, lon: -123.9120 },
      { name: 'Merry Is.',      lat: 49.4718, lon: -123.9128 },
      { name: 'Secret Cove',    lat: 49.5395, lon: -123.9600 },
      { name: 'Frenchmans Cove', lat: 49.4990, lon: -123.9050 },
      { name: 'Redrooffs',      lat: 49.4890, lon: -123.8760 },
      { name: 'Trail Bay',      lat: 49.4700, lon: -123.7600 },
    ],
    marinePoint: { name: 'Malaspina Strait', lat: 49.55, lon: -124.05 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Strait of Georgia — north of Nanaimo', siteId: '14200', mapId: '02' },
    ],
    windy: { lat: 49.51, lon: -123.95, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?49.51,-123.95,11' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/halfmoon-bay' },
      { label: 'DFO tides — 07830 Halfmoon Bay ↗', href: 'https://www.tides.gc.ca/en/stations/07830' },
    ],
  } satisfies StationConfig,
  sar14: {
    slug: 'sar14',
    brand: {
      short: 'RCMSAR 14 · Gibsons',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 14 Gibsons — Local Conditions',
      description: 'RCMSAR Unit 14 Gibsons (Sunshine Coast, Howe Sound entrance) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 14 Gibsons conditions',
    },
    labels: {
      windSub: 'Gibsons',
      seaSub: 'Howe Sound',
      tideSub: 'Gibsons (07820)',
      tideCardHeading: 'Tide — Gibsons (07820)',
      sunFootnote: 'Computed locally (SunCalc) for Gibsons.',
      forecastLocation: 'Gibsons',
      marineWarningLocation: 'Howe Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Gibsons Harbour', lat: 49.4020, lon: -123.5050 },
    tideStationId: '5cebf1de3d0f4a073c4bb950',
    points: [
      { name: 'Gibsons Harbour', lat: 49.4020, lon: -123.5050 },
      { name: 'Grantham\'s',     lat: 49.4185, lon: -123.4790 },
      { name: 'Keats Is.',       lat: 49.4009, lon: -123.4547 },
      { name: 'Gambier Is.',     lat: 49.4530, lon: -123.4020 },
      { name: 'Roberts Creek',   lat: 49.4190, lon: -123.6420 },
      { name: 'Bowen Is.',       lat: 49.3826, lon: -123.3300 },
      { name: 'Anvil Is.',       lat: 49.5745, lon: -123.3049 },
    ],
    marinePoint: { name: 'Howe Sound entrance', lat: 49.40, lon: -123.40 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Howe Sound',                             siteId: '14400', mapId: '02' },
      { label: 'Strait of Georgia — south of Nanaimo',   siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 49.40, lon: -123.45, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',    href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',             href: 'https://www.windy.com/?49.40,-123.45,11' },
      { label: 'Weather Network — hourly ↗',   href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/gibsons' },
      { label: 'DFO tides — 07820 Gibsons ↗',  href: 'https://www.tides.gc.ca/en/stations/07820' },
    ],
  } satisfies StationConfig,
  sar20: {
    slug: 'sar20',
    brand: {
      short: 'RCMSAR 20 · Pender Island',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 20 Pender Island — Local Conditions',
      description: 'RCMSAR Unit 20 Pender Island (Gulf Islands) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 20 Pender Island conditions',
    },
    labels: {
      windSub: 'Pender Island',
      seaSub: 'Boundary Pass',
      tideSub: 'Bedwell Harbour (07350)',
      tideCardHeading: 'Tide — Bedwell Harbour (07350)',
      sunFootnote: 'Computed locally (SunCalc) for Pender Island.',
      forecastLocation: 'Pender Island',
      marineWarningLocation: 'Boundary Pass',
    },
    tz: 'America/Vancouver',
    center: { name: 'Razor Point', lat: 48.7890, lon: -123.2600 },
    tideStationId: '5cebf1df3d0f4a073c4bbd39',
    points: [
      { name: 'Razor Point',      lat: 48.7890, lon: -123.2600 },
      { name: 'Bedwell Harbour',  lat: 48.7478, lon: -123.2273 },
      { name: 'Port Browning',    lat: 48.7800, lon: -123.2820 },
      { name: 'Otter Bay',        lat: 48.7986, lon: -123.3120 },
      { name: 'Hope Bay',         lat: 48.8034, lon: -123.2759 },
      { name: 'Boundary Pass',    lat: 48.7500, lon: -123.1500 },
      { name: 'Blunden Is.',      lat: 48.7645, lon: -123.2265 },
      { name: 'Tilly Point',      lat: 48.7318, lon: -123.2380 },
    ],
    marinePoint: { name: 'Boundary Pass', lat: 48.74, lon: -123.15 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
    ],
    windy: { lat: 48.78, lon: -123.25, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',            href: 'https://windisgood.com/island-map2.html' },
      { label: 'WindIsGood — Gulf Islands ↗',          href: 'https://windisgood.com/gulf-islands.html' },
      { label: 'Windy.com full ↗',                     href: 'https://www.windy.com/?48.78,-123.25,11' },
      { label: 'Weather Network — hourly ↗',           href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/pender-island' },
      { label: 'DFO tides — 07350 Bedwell Harbour ↗',  href: 'https://www.tides.gc.ca/en/stations/07350' },
    ],
  } satisfies StationConfig,
  sar27: {
    slug: 'sar27',
    brand: {
      short: 'RCMSAR 27 · Nanaimo',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar27/logo.jpg',
      logoAlt: 'RCMSAR 27 Nanaimo',
      faviconSrc: '/stations/sar27/favicon.jpg',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 27 Nanaimo — Local Conditions',
      description: 'RCMSAR Unit 27 Nanaimo (Brechin Boat Ramp, Departure Bay) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 27 Nanaimo conditions',
    },
    labels: {
      windSub: 'Nanaimo',
      seaSub: 'Strait of Georgia',
      tideSub: 'Nanaimo Harbour (07917)',
      tideCardHeading: 'Tide — Nanaimo Harbour (07917)',
      sunFootnote: 'Computed locally (SunCalc) for Nanaimo.',
      forecastLocation: 'Nanaimo',
      marineWarningLocation: 'Strait of Georgia',
    },
    tz: 'America/Vancouver',
    center: { name: 'Brechin Boat Ramp', lat: 49.1800, lon: -123.9380 },
    tideStationId: '5cebf1de3d0f4a073c4bb96d',
    points: [
      { name: 'Brechin Boat Ramp', lat: 49.1800, lon: -123.9380 },
      { name: 'Departure Bay',    lat: 49.2050, lon: -123.9530 },
      { name: 'Nanaimo Harbour',  lat: 49.1628, lon: -123.9235 },
      { name: 'Newcastle Is.',    lat: 49.1802, lon: -123.9354 },
      { name: 'Protection Is.',   lat: 49.1650, lon: -123.9059 },
      { name: 'Entrance Is.',     lat: 49.2088, lon: -123.8091 },
      { name: 'Snake Is.',        lat: 49.2172, lon: -123.8814 },
      { name: 'Dodd Narrows',     lat: 49.1344, lon: -123.8171 },
      { name: 'Gabriola Pass',    lat: 49.1291, lon: -123.7043 },
    ],
    marinePoint: { name: 'Strait of Georgia — mid', lat: 49.20, lon: -123.75 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Strait of Georgia — north of Nanaimo', siteId: '14200', mapId: '02' },
    ],
    windy: { lat: 49.18, lon: -123.90, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',           href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                    href: 'https://www.windy.com/?49.18,-123.90,11' },
      { label: 'Weather Network — hourly ↗',          href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/nanaimo' },
      { label: 'DFO tides — 07917 Nanaimo Harbour ↗', href: 'https://www.tides.gc.ca/en/stations/07917' },
    ],
  } satisfies StationConfig,
  sar29: {
    slug: 'sar29',
    brand: {
      short: 'RCMSAR 29 · Ladysmith',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar29/logo.png',
      logoAlt: 'RCMSAR 29 Ladysmith',
      faviconSrc: '/stations/sar29/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 29 Ladysmith — Local Conditions',
      description: 'RCMSAR Unit 29 Ladysmith (Ladysmith Harbour, Stuart Channel) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 29 Ladysmith conditions',
    },
    labels: {
      windSub: 'Ladysmith',
      seaSub: 'Stuart Channel',
      tideSub: 'Ladysmith (07460)',
      tideCardHeading: 'Tide — Ladysmith (07460)',
      sunFootnote: 'Computed locally (SunCalc) for Ladysmith.',
      forecastLocation: 'Ladysmith',
      marineWarningLocation: 'Stuart Channel',
    },
    tz: 'America/Vancouver',
    center: { name: 'Ladysmith Harbour', lat: 48.9980, lon: -123.8160 },
    tideStationId: '5cebf1e03d0f4a073c4bbd47',
    points: [
      { name: 'Ladysmith Harbour', lat: 48.9980, lon: -123.8160 },
      { name: 'Slack Pt',       lat: 48.9840, lon: -123.7800 },
      { name: 'Coffin Pt',      lat: 49.0110, lon: -123.7970 },
      { name: 'Yellow Pt',      lat: 49.0620, lon: -123.7534 },
      { name: 'Kulleet Bay',    lat: 48.9370, lon: -123.7770 },
      { name: 'Chemainus',      lat: 48.9256, lon: -123.7144 },
      { name: 'Boat Harbour',   lat: 49.0900, lon: -123.7982 },
      { name: 'Thetis Is.',     lat: 48.9930, lon: -123.6620 },
    ],
    marinePoint: { name: 'Stuart Channel', lat: 48.95, lon: -123.68 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 48.99, lon: -123.75, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',       href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                href: 'https://www.windy.com/?48.99,-123.75,11' },
      { label: 'Weather Network — hourly ↗',      href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/ladysmith' },
      { label: 'DFO tides — 07460 Ladysmith ↗',   href: 'https://www.tides.gc.ca/en/stations/07460' },
      { label: 'DFO tides — 07455 Chemainus ↗',   href: 'https://www.tides.gc.ca/en/stations/07455' },
    ],
  } satisfies StationConfig,
  sar31: {
    slug: 'sar31',
    brand: {
      short: 'RCMSAR 31 · Brentwood Bay',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar31/logo.png',
      logoAlt: 'RCMSAR 31 Brentwood Bay',
      faviconSrc: '/stations/sar31/favicon.jpg',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 31 Brentwood Bay — Local Conditions',
      description: 'RCMSAR Unit 31 Brentwood Bay (Saanich Inlet) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 31 Brentwood Bay conditions',
    },
    labels: {
      windSub: 'Brentwood Bay',
      seaSub: 'Saanich Inlet',
      tideSub: 'Brentwood Bay (07280)',
      tideCardHeading: 'Tide — Brentwood Bay (07280)',
      sunFootnote: 'Computed locally (SunCalc) for Brentwood Bay.',
      forecastLocation: 'Brentwood Bay',
      marineWarningLocation: 'Saanich Inlet',
    },
    tz: 'America/Vancouver',
    center: { name: 'Brentwood Bay', lat: 48.5780, lon: -123.4670 },
    tideStationId: '5dd30650e0fdc4b9b4be6b74',
    points: [
      { name: 'Brentwood Bay',  lat: 48.5780, lon: -123.4670 },
      { name: 'Verdier Pt',     lat: 48.5850, lon: -123.4640 },
      { name: 'Willis Pt',      lat: 48.5590, lon: -123.5170 },
      { name: 'Coles Bay',      lat: 48.6300, lon: -123.4980 },
      { name: 'Patricia Bay',   lat: 48.6536, lon: -123.4515 },
      { name: 'Squally Reach',  lat: 48.5400, lon: -123.5500 },
      { name: 'Finlayson Arm',  lat: 48.4966, lon: -123.5529 },
      { name: 'Piers Is.',      lat: 48.6900, lon: -123.4300 },
    ],
    marinePoint: { name: 'Saanich Inlet', lat: 48.58, lon: -123.51 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 48.58, lon: -123.48, zoom: 12 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?48.58,-123.48,12' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/central-saanich' },
      { label: 'DFO tides — 07280 Brentwood Bay ↗', href: 'https://www.tides.gc.ca/en/stations/07280' },
      { label: 'DFO tides — 07277 Patricia Bay ↗', href: 'https://www.tides.gc.ca/en/stations/07277' },
    ],
  } satisfies StationConfig,
  sar34: {
    slug: 'sar34',
    brand: {
      short: 'RCMSAR 34 · Cowichan Bay',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar34/logo.png',
      logoAlt: 'RCMSAR 34 Cowichan Bay',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 34 Cowichan Bay — Local Conditions',
      description: 'RCMSAR Unit 34 Cowichan Bay (Fisherman\'s Wharf, Cowichan Bay) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 34 Cowichan Bay conditions',
    },
    labels: {
      windSub: 'Cowichan Bay',
      seaSub: 'Sansum Narrows',
      tideSub: 'Cowichan Bay (07310)',
      tideCardHeading: 'Tide — Cowichan Bay (07310)',
      sunFootnote: 'Computed locally (SunCalc) for Cowichan Bay.',
      forecastLocation: 'Cowichan Bay',
      marineWarningLocation: 'Cowichan Bay',
    },
    tz: 'America/Vancouver',
    center: { name: 'Cowichan Bay', lat: 48.7404, lon: -123.6184 },
    tideStationId: '5cebf1df3d0f4a073c4bbd31',
    points: [
      { name: 'Cowichan Bay',    lat: 48.7404, lon: -123.6184 },
      { name: 'Mill Bay',        lat: 48.6469, lon: -123.5476 },
      { name: 'Cherry Pt',       lat: 48.7120, lon: -123.5850 },
      { name: 'Genoa Bay',       lat: 48.7643, lon: -123.5921 },
      { name: 'Sansum Narrows',  lat: 48.8080, lon: -123.5860 },
      { name: 'Musgrave Ldg',    lat: 48.7620, lon: -123.5770 },
      { name: 'Separation Pt',   lat: 48.7370, lon: -123.5600 },
      { name: 'Maple Bay',       lat: 48.8157, lon: -123.6096 },
    ],
    marinePoint: { name: 'Sansum Narrows', lat: 48.80, lon: -123.59 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
    ],
    windy: { lat: 48.74, lon: -123.60, zoom: 12 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',        href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                 href: 'https://www.windy.com/?48.74,-123.60,12' },
      { label: 'Weather Network — hourly ↗',       href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/duncan' },
      { label: 'DFO tides — 07310 Cowichan Bay ↗', href: 'https://www.tides.gc.ca/en/stations/07310' },
      { label: 'DFO tides — 07315 Maple Bay ↗',    href: 'https://www.tides.gc.ca/en/stations/07315' },
    ],
  } satisfies StationConfig,
  sar35: {
    slug: 'sar35',
    brand: {
      short: 'RCMSAR 35 · Victoria',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar35/logo.png',
      logoAlt: 'RCMSAR 35 Victoria Marine Rescue Society',
      faviconSrc: '/stations/sar35/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 35 Victoria — Local Conditions',
      description: 'RCMSAR Unit 35 Victoria (Victoria Marine Rescue Society) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 35 Victoria conditions',
    },
    labels: {
      windSub: 'Victoria',
      seaSub: 'Juan de Fuca',
      tideSub: 'Victoria Harbour (07120)',
      tideCardHeading: 'Tide — Victoria Harbour (07120)',
      sunFootnote: 'Computed locally (SunCalc) for Victoria.',
      forecastLocation: 'Victoria',
      marineWarningLocation: 'Victoria',
    },
    tz: 'America/Vancouver',
    center: { name: 'Victoria Harbour', lat: 48.4240, lon: -123.3710 },
    tideStationId: '5cebf1df3d0f4a073c4bbd1e',
    points: [
      { name: 'Victoria Harbour', lat: 48.4240, lon: -123.3710 },
      { name: 'Ogden Pt',        lat: 48.4123, lon: -123.3874 },
      { name: 'Clover Pt',       lat: 48.4038, lon: -123.3486 },
      { name: 'Trial Is.',       lat: 48.3939, lon: -123.3053 },
      { name: 'Chain Is.',       lat: 48.4172, lon: -123.3378 },
      { name: 'Discovery Is.',   lat: 48.4247, lon: -123.2261 },
      { name: 'Fisgard',         lat: 48.4308, lon: -123.4478 },
      { name: 'Esquimalt',       lat: 48.4322, lon: -123.4385 },
      { name: 'Race Passage',    lat: 48.3067, lon: -123.5367 },
    ],
    marinePoint: { name: 'Juan de Fuca — east', lat: 48.35, lon: -123.35 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
      { label: 'Juan de Fuca Strait — east entrance',  siteId: '07003', mapId: '02' },
    ],
    windy: { lat: 48.42, lon: -123.37, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',          href: 'https://windisgood.com/island-map2.html' },
      { label: 'WindIsGood — Dallas Road ↗',         href: 'https://windisgood.com/dallas-road.html' },
      { label: 'Windy.com full ↗',                   href: 'https://www.windy.com/?48.42,-123.37,11' },
      { label: 'Weather Network — hourly ↗',         href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/victoria' },
      { label: 'DFO tides — 07120 Victoria Hbr ↗',   href: 'https://www.tides.gc.ca/en/stations/07120' },
    ],
  } satisfies StationConfig,
  sar36: {
    slug: 'sar36',
    brand: {
      short: 'RCMSAR 36 · Sidney',
      tagline: 'Local Marine Conditions',
      faviconSrc: '/stations/sar36/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 36 Sidney — Local Conditions',
      description: 'RCMSAR Unit 36 Sidney (Saanich Peninsula) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 36 Sidney conditions',
    },
    labels: {
      windSub: 'Sidney',
      seaSub: 'Haro Strait',
      tideSub: 'Sidney (07260)',
      tideCardHeading: 'Tide — Sidney (07260)',
      sunFootnote: 'Computed locally (SunCalc) for Sidney.',
      forecastLocation: 'Sidney',
      marineWarningLocation: 'Haro Strait',
    },
    tz: 'America/Vancouver',
    center: { name: 'Sidney', lat: 48.6530, lon: -123.3930 },
    tideStationId: '5cebf1df3d0f4a073c4bbd26',
    points: [
      { name: 'Sidney',          lat: 48.6530, lon: -123.3930 },
      { name: 'Roberts Bay',     lat: 48.6620, lon: -123.4020 },
      { name: 'Sidney Spit',     lat: 48.6469, lon: -123.3459 },
      { name: 'Portland Is.',    lat: 48.7360, lon: -123.3680 },
      { name: 'Piers Is.',       lat: 48.6900, lon: -123.4300 },
      { name: 'Swartz Bay',      lat: 48.6892, lon: -123.4108 },
      { name: 'Saanichton Bay',  lat: 48.5989, lon: -123.3885 },
      { name: 'D\'Arcy Is.',     lat: 48.5730, lon: -123.2810 },
    ],
    marinePoint: { name: 'Haro Strait', lat: 48.60, lon: -123.30 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Haro Strait',                          siteId: '06100', mapId: '02' },
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 48.65, lon: -123.39, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',    href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',             href: 'https://www.windy.com/?48.65,-123.39,11' },
      { label: 'Weather Network — hourly ↗',   href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/sidney' },
      { label: 'DFO tides — 07260 Sidney ↗',   href: 'https://www.tides.gc.ca/en/stations/07260' },
    ],
  } satisfies StationConfig,
  sar37: {
    slug: 'sar37',
    brand: {
      short: 'RCMSAR 37 · Sooke',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 37 Sooke — Local Conditions',
      description: 'RCMSAR Unit 37 Sooke (Juan de Fuca Marine Rescue Society, East Sooke) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 37 Sooke conditions',
    },
    labels: {
      windSub: 'Sooke',
      seaSub: 'Juan de Fuca',
      tideSub: 'Sooke (07020)',
      tideCardHeading: 'Tide — Sooke (07020)',
      sunFootnote: 'Computed locally (SunCalc) for Sooke.',
      forecastLocation: 'Sooke',
      marineWarningLocation: 'Sooke',
    },
    tz: 'America/Vancouver',
    center: { name: 'East Sooke', lat: 48.3700, lon: -123.7260 },
    tideStationId: '5cebf1df3d0f4a073c4bbd0f',
    points: [
      { name: 'East Sooke',      lat: 48.3700, lon: -123.7260 },
      { name: 'Sooke Basin',     lat: 48.3742, lon: -123.6818 },
      { name: 'Sooke Harbour',   lat: 48.3695, lon: -123.7480 },
      { name: 'Whiffin Spit',    lat: 48.3620, lon: -123.7280 },
      { name: 'Otter Pt',        lat: 48.3550, lon: -123.8010 },
      { name: 'Beechey Head',    lat: 48.3335, lon: -123.6486 },
      { name: 'Sheringham Pt',   lat: 48.3771, lon: -123.9212 },
      { name: 'Muir Cr.',        lat: 48.3830, lon: -123.8830 },
    ],
    marinePoint: { name: 'Juan de Fuca', lat: 48.30, lon: -123.75 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Juan de Fuca Strait — east entrance',  siteId: '07003', mapId: '02' },
      { label: 'Juan de Fuca Strait — central strait', siteId: '07010', mapId: '02' },
    ],
    windy: { lat: 48.37, lon: -123.73, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',    href: 'https://windisgood.com/island-map2.html' },
      { label: 'WindIsGood — Sooke ↗',         href: 'https://windisgood.com/sooke-webcam.html' },
      { label: 'Windy.com full ↗',             href: 'https://www.windy.com/?48.37,-123.73,11' },
      { label: 'Weather Network — hourly ↗',   href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/sooke' },
      { label: 'DFO tides — 07020 Sooke ↗',    href: 'https://www.tides.gc.ca/en/stations/07020' },
    ],
  } satisfies StationConfig,
  sar38: {
    slug: 'sar38',
    brand: {
      short: 'RCMSAR 38 · Ucluelet',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 38 Ucluelet — Local Conditions',
      description: 'RCMSAR Unit 38 Ucluelet (west coast Vancouver Island) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 38 Ucluelet conditions',
    },
    labels: {
      windSub: 'Ucluelet',
      seaSub: 'Barkley Sound',
      tideSub: 'Ucluelet (08595)',
      tideCardHeading: 'Tide — Ucluelet (08595)',
      sunFootnote: 'Computed locally (SunCalc) for Ucluelet.',
      forecastLocation: 'Ucluelet',
      marineWarningLocation: 'Barkley Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Ucluelet', lat: 48.9400, lon: -125.5450 },
    tideStationId: '5cebf1e23d0f4a073c4bc075',
    points: [
      { name: 'Ucluelet Harbour', lat: 48.9400, lon: -125.5450 },
      { name: 'Amphitrite Pt',    lat: 48.9195, lon: -125.5410 },
      { name: 'Effingham Is.',    lat: 48.8780, lon: -125.3130 },
      { name: 'Sechart Ch.',      lat: 48.9350, lon: -125.2900 },
      { name: 'Broken Group',     lat: 48.8830, lon: -125.3400 },
      { name: 'Loudoun Ch.',      lat: 48.9020, lon: -125.4600 },
    ],
    marinePoint: { name: 'Barkley Sound', lat: 48.90, lon: -125.40 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 48.94, lon: -125.55, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',              href: 'https://www.windy.com/?48.94,-125.55,11' },
      { label: 'Weather Network — hourly ↗',    href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/ucluelet' },
      { label: 'DFO tides — 08595 Ucluelet ↗',  href: 'https://www.tides.gc.ca/en/stations/08595' },
      { label: 'ECCC marine — WCVI south ↗',    href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar39: {
    slug: 'sar39',
    brand: {
      short: 'RCMSAR 39 · Port Alberni',
      tagline: 'Local Marine Conditions',
      faviconSrc: '/stations/sar39/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 39 Port Alberni — Local Conditions',
      description: 'RCMSAR Unit 39 Port Alberni (Alberni Inlet) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 39 Port Alberni conditions',
    },
    labels: {
      windSub: 'Port Alberni',
      seaSub: 'Alberni Inlet',
      tideSub: 'Port Alberni (08575)',
      tideCardHeading: 'Tide — Port Alberni (08575)',
      sunFootnote: 'Computed locally (SunCalc) for Port Alberni.',
      forecastLocation: 'Port Alberni',
      marineWarningLocation: 'Alberni Inlet',
    },
    tz: 'America/Vancouver',
    center: { name: 'Port Alberni', lat: 49.2340, lon: -124.8080 },
    tideStationId: '5cebf1e23d0f4a073c4bc06f',
    points: [
      { name: 'Port Alberni',    lat: 49.2340, lon: -124.8080 },
      { name: 'Somass R. mouth', lat: 49.2450, lon: -124.8280 },
      { name: 'Franklin R.',     lat: 49.1080, lon: -124.8120 },
      { name: 'Sproat Narrows',  lat: 49.2660, lon: -124.8090 },
      { name: 'Uchucklesit',     lat: 49.0170, lon: -125.0500 },
      { name: 'Bamfield',        lat: 48.8360, lon: -125.1360 },
    ],
    marinePoint: { name: 'Alberni Inlet', lat: 49.15, lon: -124.85 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 49.23, lon: -124.80, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',                  href: 'https://www.windy.com/?49.23,-124.80,11' },
      { label: 'Weather Network — hourly ↗',        href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/port-alberni' },
      { label: 'DFO tides — 08575 Port Alberni ↗',  href: 'https://www.tides.gc.ca/en/stations/08575' },
      { label: 'DFO tides — 08545 Bamfield ↗',      href: 'https://www.tides.gc.ca/en/stations/08545' },
      { label: 'ECCC marine — WCVI south ↗',        href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar45: {
    slug: 'sar45',
    brand: {
      short: 'RCMSAR 45 · Masset',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 45 Masset — Local Conditions',
      description: 'RCMSAR Unit 45 Masset (Haida Gwaii) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 45 Masset conditions',
    },
    labels: {
      windSub: 'Masset',
      seaSub: 'Dixon Entrance',
      tideSub: 'Masset (09910)',
      tideCardHeading: 'Tide — Masset (09910)',
      sunFootnote: 'Computed locally (SunCalc) for Masset.',
      forecastLocation: 'Masset',
      marineWarningLocation: 'Dixon Entrance',
    },
    tz: 'America/Vancouver',
    center: { name: 'Masset', lat: 54.0210, lon: -132.1440 },
    tideStationId: '5cebf1de3d0f4a073c4bba44',
    points: [
      { name: 'Masset',         lat: 54.0210, lon: -132.1440 },
      { name: 'Old Massett',    lat: 54.0270, lon: -132.1660 },
      { name: 'Masset Inlet',   lat: 53.9200, lon: -132.1500 },
      { name: 'McIntyre Bay',   lat: 54.0620, lon: -132.0100 },
      { name: 'Rose Spit',      lat: 54.1620, lon: -131.6620 },
    ],
    marinePoint: { name: 'Dixon Entrance', lat: 54.15, lon: -132.20 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 54.02, lon: -132.14, zoom: 10 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',              href: 'https://www.windy.com/?54.02,-132.14,10' },
      { label: 'Weather Network — hourly ↗',    href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/masset' },
      { label: 'DFO tides — 09910 Masset ↗',    href: 'https://www.tides.gc.ca/en/stations/09910' },
      { label: 'ECCC marine — North coast ↗',   href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar59: {
    slug: 'sar59',
    brand: {
      short: 'RCMSAR 59 · Deep Bay',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar59/logo.png',
      logoAlt: 'RCMSAR 59 Deep Bay',
      faviconSrc: '/stations/sar59/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 59 Deep Bay — Local Conditions',
      description: 'RCMSAR Unit 59 Deep Bay (Baynes Sound, Vancouver Island east coast) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 59 Deep Bay conditions',
    },
    labels: {
      windSub: 'Deep Bay',
      seaSub: 'Baynes Sound',
      tideSub: 'Hornby Island (07953)',
      tideCardHeading: 'Tide — Hornby Island (07953)',
      sunFootnote: 'Computed locally (SunCalc) for Deep Bay.',
      forecastLocation: 'Deep Bay',
      marineWarningLocation: 'Baynes Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Deep Bay', lat: 49.4640, lon: -124.7340 },
    tideStationId: '5cebf1de3d0f4a073c4bb975',
    points: [
      { name: 'Deep Bay',       lat: 49.4640, lon: -124.7340 },
      { name: 'Chrome Is.',     lat: 49.4710, lon: -124.6910 },
      { name: 'Denman Is. (Boyle Pt)', lat: 49.4820, lon: -124.7020 },
      { name: 'Hornby Is. (Ford\'s Cove)', lat: 49.5010, lon: -124.7080 },
      { name: 'Baynes Sound',   lat: 49.5100, lon: -124.7800 },
      { name: 'Fanny Bay',      lat: 49.5010, lon: -124.8110 },
      { name: 'Union Bay',      lat: 49.5850, lon: -124.8800 },
    ],
    marinePoint: { name: 'Strait of Georgia — mid', lat: 49.55, lon: -124.60 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — north of Nanaimo', siteId: '14200', mapId: '02' },
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 49.46, lon: -124.73, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',      href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',               href: 'https://www.windy.com/?49.46,-124.73,11' },
      { label: 'Weather Network — hourly ↗',     href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/bowser' },
      { label: 'DFO tides — 07953 Hornby Is. ↗', href: 'https://www.tides.gc.ca/en/stations/07953' },
      { label: 'DFO tides — 07955 Denman Is. ↗', href: 'https://www.tides.gc.ca/en/stations/07955' },
    ],
  } satisfies StationConfig,
  sar60: {
    slug: 'sar60',
    brand: {
      short: 'RCMSAR 60 · Comox',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 60 Comox — Local Conditions',
      description: 'RCMSAR Unit 60 Comox (Comox Municipal Marina) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 60 Comox conditions',
    },
    labels: {
      windSub: 'Comox',
      seaSub: 'Strait of Georgia',
      tideSub: 'Comox (07965)',
      tideCardHeading: 'Tide — Comox (07965)',
      sunFootnote: 'Computed locally (SunCalc) for Comox.',
      forecastLocation: 'Comox',
      marineWarningLocation: 'Comox',
    },
    tz: 'America/Vancouver',
    center: { name: 'Comox Marina', lat: 49.6740, lon: -124.9280 },
    tideStationId: '5cebf1de3d0f4a073c4bb979',
    points: [
      { name: 'Comox Marina',   lat: 49.6740, lon: -124.9280 },
      { name: 'Comox Harbour',  lat: 49.6620, lon: -124.9350 },
      { name: 'Goose Spit',     lat: 49.6595, lon: -124.9032 },
      { name: 'Cape Lazo',      lat: 49.7020, lon: -124.8500 },
      { name: 'Kye Bay',        lat: 49.7160, lon: -124.8760 },
      { name: 'Little River',   lat: 49.7410, lon: -124.9230 },
      { name: 'Denman Is.',     lat: 49.5345, lon: -124.8209 },
      { name: 'Baynes Sound',   lat: 49.5100, lon: -124.7800 },
    ],
    marinePoint: { name: 'Strait of Georgia — Comox', lat: 49.75, lon: -124.75 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — north of Nanaimo', siteId: '14200', mapId: '02' },
    ],
    windy: { lat: 49.67, lon: -124.92, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',    href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',             href: 'https://www.windy.com/?49.67,-124.92,11' },
      { label: 'Weather Network — hourly ↗',   href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/comox' },
      { label: 'DFO tides — 07965 Comox ↗',    href: 'https://www.tides.gc.ca/en/stations/07965' },
    ],
  } satisfies StationConfig,
  sar61: {
    slug: 'sar61',
    brand: {
      short: 'RCMSAR 61 · Pender Harbour',
      tagline: 'Local Marine Conditions',
      logoSrc: '/stations/sar61/logo.png',
      logoAlt: 'RCMSAR 61 Pender Harbour Spirit',
      faviconSrc: '/stations/sar61/favicon.ico',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 61 Pender Harbour — Local Conditions',
      description: 'RCMSAR Unit 61 Pender Harbour (Garden Bay, Sunshine Coast) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 61 Pender Harbour conditions',
    },
    labels: {
      windSub: 'Pender Harbour',
      seaSub: 'Malaspina Strait',
      tideSub: 'Irvines Landing (07836)',
      tideCardHeading: 'Tide — Irvines Landing (07836)',
      sunFootnote: 'Computed locally (SunCalc) for Pender Harbour.',
      forecastLocation: 'Pender Harbour',
      marineWarningLocation: 'Strait of Georgia',
    },
    tz: 'America/Vancouver',
    center: { name: 'Garden Bay', lat: 49.6330, lon: -124.0280 },
    tideStationId: '5cebf1de3d0f4a073c4bb954',
    points: [
      { name: 'Garden Bay',       lat: 49.6330, lon: -124.0280 },
      { name: 'Irvines Landing',  lat: 49.6330, lon: -124.0580 },
      { name: 'Madeira Park',     lat: 49.6234, lon: -124.0341 },
      { name: 'Francis Peninsula', lat: 49.6135, lon: -124.0620 },
      { name: 'Bargain Bay',      lat: 49.6120, lon: -124.0800 },
      { name: 'Egmont',           lat: 49.7490, lon: -123.9300 },
      { name: 'Blind Bay',        lat: 49.7160, lon: -124.1790 },
    ],
    marinePoint: { name: 'Malaspina Strait', lat: 49.65, lon: -124.15 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — north of Nanaimo', siteId: '14200', mapId: '02' },
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
    ],
    windy: { lat: 49.63, lon: -124.05, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',            href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',                     href: 'https://www.windy.com/?49.63,-124.05,11' },
      { label: 'Weather Network — hourly ↗',           href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/pender-harbour' },
      { label: 'DFO tides — 07836 Irvines Landing ↗',  href: 'https://www.tides.gc.ca/en/stations/07836' },
    ],
  } satisfies StationConfig,
  sar63: {
    slug: 'sar63',
    brand: {
      short: 'RCMSAR 63 · Kitimat',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 63 Kitimat — Local Conditions',
      description: 'RCMSAR Unit 63 Kitimat (Douglas Channel — Kitimat Arm) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 63 Kitimat conditions',
    },
    labels: {
      windSub: 'Kitimat',
      seaSub: 'Douglas Channel',
      tideSub: 'Kitimat (09140)',
      tideCardHeading: 'Tide — Kitimat (09140)',
      sunFootnote: 'Computed locally (SunCalc) for Kitimat.',
      forecastLocation: 'Kitimat',
      marineWarningLocation: 'Douglas Channel',
    },
    tz: 'America/Vancouver',
    center: { name: 'MK Bay Marina', lat: 53.9940, lon: -128.7060 },
    tideStationId: '5cebf1de3d0f4a073c4bb925',
    points: [
      { name: 'MK Bay Marina',    lat: 53.9940, lon: -128.7060 },
      { name: 'Kitamaat Village', lat: 53.9720, lon: -128.6580 },
      { name: 'Kitimat R. mouth', lat: 54.0090, lon: -128.6970 },
      { name: 'Emsley Cove',      lat: 53.9600, lon: -128.7150 },
      { name: 'Douglas Channel',  lat: 53.7500, lon: -128.9000 },
    ],
    marinePoint: { name: 'Douglas Channel', lat: 53.85, lon: -128.85 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 53.99, lon: -128.70, zoom: 10 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',              href: 'https://www.windy.com/?53.99,-128.70,10' },
      { label: 'Weather Network — hourly ↗',    href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/kitimat' },
      { label: 'DFO tides — 09140 Kitimat ↗',   href: 'https://www.tides.gc.ca/en/stations/09140' },
      { label: 'ECCC marine — North coast ↗',   href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar64: {
    slug: 'sar64',
    brand: {
      short: 'RCMSAR 64 · Prince Rupert',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 64 Prince Rupert — Local Conditions',
      description: 'RCMSAR Unit 64 Prince Rupert (Chatham Sound, north coast BC) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 64 Prince Rupert conditions',
    },
    labels: {
      windSub: 'Prince Rupert',
      seaSub: 'Chatham Sound',
      tideSub: 'Prince Rupert (09354)',
      tideCardHeading: 'Tide — Prince Rupert (09354)',
      sunFootnote: 'Computed locally (SunCalc) for Prince Rupert.',
      forecastLocation: 'Prince Rupert',
      marineWarningLocation: 'Chatham Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Prince Rupert', lat: 54.3120, lon: -130.3250 },
    tideStationId: '5cebf1de3d0f4a073c4bba06',
    points: [
      { name: 'Prince Rupert Hbr', lat: 54.3120, lon: -130.3250 },
      { name: 'Seal Cove',         lat: 54.3311, lon: -130.2796 },
      { name: 'Fairview Terminal', lat: 54.2903, lon: -130.3600 },
      { name: 'Digby Is.',         lat: 54.2790, lon: -130.4300 },
      { name: 'Metlakatla',        lat: 54.3300, lon: -130.4500 },
      { name: 'Port Edward',       lat: 54.2290, lon: -130.2960 },
      { name: 'Ridley Terminal',   lat: 54.2350, lon: -130.3200 },
    ],
    marinePoint: { name: 'Chatham Sound', lat: 54.35, lon: -130.50 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 54.31, lon: -130.32, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',                  href: 'https://www.windy.com/?54.31,-130.32,11' },
      { label: 'Weather Network — hourly ↗',        href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/prince-rupert' },
      { label: 'DFO tides — 09354 Prince Rupert ↗', href: 'https://www.tides.gc.ca/en/stations/09354' },
      { label: 'ECCC marine — North coast ↗',       href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar65: {
    slug: 'sar65',
    brand: {
      short: 'RCMSAR 65 · Lax Kw\'alaams',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 65 Lax Kw\'alaams — Local Conditions',
      description: 'RCMSAR Unit 65 Lax Kw\'alaams (north coast BC) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 65 Lax Kw\'alaams conditions',
    },
    labels: {
      windSub: 'Lax Kw\'alaams',
      seaSub: 'Chatham Sound',
      tideSub: 'Lax Kw\'alaams (09390)',
      tideCardHeading: 'Tide — Lax Kw\'alaams (09390)',
      sunFootnote: 'Computed locally (SunCalc) for Lax Kw\'alaams.',
      forecastLocation: 'Lax Kw\'alaams',
      marineWarningLocation: 'Chatham Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Lax Kw\'alaams', lat: 54.5600, lon: -130.4310 },
    tideStationId: '5cebf1de3d0f4a073c4bba08',
    points: [
      { name: 'Lax Kw\'alaams',   lat: 54.5600, lon: -130.4310 },
      { name: 'Tugwell Is.',      lat: 54.5720, lon: -130.5800 },
      { name: 'Melville Is.',     lat: 54.6220, lon: -130.5800 },
      { name: 'Big Bay',          lat: 54.5470, lon: -130.4550 },
      { name: 'Trail Bay',        lat: 54.5830, lon: -130.3570 },
    ],
    marinePoint: { name: 'Chatham Sound — north', lat: 54.65, lon: -130.55 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 54.56, lon: -130.43, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',                    href: 'https://www.windy.com/?54.56,-130.43,11' },
      { label: 'Weather Network — hourly ↗',          href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/prince-rupert' },
      { label: 'DFO tides — 09390 Lax Kw\'alaams ↗',  href: 'https://www.tides.gc.ca/en/stations/09390' },
      { label: 'ECCC marine — North coast ↗',         href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar70: {
    slug: 'sar70',
    brand: {
      short: 'RCMSAR 70 · Hartley Bay',
      tagline: 'Local Marine Conditions',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 70 Hartley Bay — Local Conditions',
      description: 'RCMSAR Unit 70 Hartley Bay (Gitga\'at community, north coast BC) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 70 Hartley Bay conditions',
    },
    labels: {
      windSub: 'Hartley Bay',
      seaSub: 'Wright Sound',
      tideSub: 'Hartley Bay (09130)',
      tideCardHeading: 'Tide — Hartley Bay (09130)',
      sunFootnote: 'Computed locally (SunCalc) for Hartley Bay.',
      forecastLocation: 'Hartley Bay',
      marineWarningLocation: 'Wright Sound',
    },
    tz: 'America/Vancouver',
    center: { name: 'Hartley Bay', lat: 53.4242, lon: -129.2519 },
    tideStationId: '5cebf1de3d0f4a073c4bb91e',
    points: [
      { name: 'Hartley Bay',      lat: 53.4242, lon: -129.2519 },
      { name: 'Wright Sound',     lat: 53.4000, lon: -129.1500 },
      { name: 'Whale Ch.',        lat: 53.3500, lon: -129.2500 },
      { name: 'Grenville Ch. S.', lat: 53.4600, lon: -129.4500 },
      { name: 'Coghlan Anchorage', lat: 53.5100, lon: -129.4000 },
      { name: 'Douglas Ch. S.',   lat: 53.4700, lon: -129.0700 },
    ],
    marinePoint: { name: 'Wright Sound', lat: 53.42, lon: -129.20 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 53.42, lon: -129.25, zoom: 10 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',                  href: 'https://www.windy.com/?53.42,-129.25,10' },
      { label: 'DFO tides — 09130 Hartley Bay ↗',   href: 'https://www.tides.gc.ca/en/stations/09130' },
      { label: 'ECCC marine — North coast ↗',       href: 'https://weather.gc.ca/marine/region_e.html?mapID=03' },
    ],
  } satisfies StationConfig,
  sar103: {
    slug: 'sar103',
    brand: {
      short: 'RCMSAR 103 · Vancouver',
      tagline: 'SAR Prevention',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 103 Vancouver — Local Conditions',
      description: 'RCMSAR Unit 103 Vancouver (SAR Prevention, Lower Mainland) local marine conditions dashboard for wind, weather, tides, and sea state.',
      footerCredit: 'RCMSAR 103 Vancouver conditions',
    },
    labels: {
      windSub: 'English Bay',
      seaSub: 'Burrard Inlet',
      tideSub: 'Vancouver (07735)',
      tideCardHeading: 'Tide — Vancouver (07735)',
      sunFootnote: 'Computed locally (SunCalc) for Vancouver.',
      forecastLocation: 'Vancouver',
      marineWarningLocation: 'Burrard Inlet',
    },
    tz: 'America/Vancouver',
    center: { name: 'Vancouver', lat: 49.2830, lon: -123.1000 },
    tideStationId: '5cebf1de3d0f4a073c4bb943',
    points: [
      { name: 'Vancouver Hbr',   lat: 49.2863, lon: -123.0997 },
      { name: 'English Bay',     lat: 49.2830, lon: -123.1400 },
      { name: 'Kits Pt',         lat: 49.2740, lon: -123.1560 },
      { name: 'Point Grey',      lat: 49.2670, lon: -123.2620 },
      { name: 'Jericho',         lat: 49.2724, lon: -123.1900 },
      { name: 'Kitsilano',       lat: 49.2766, lon: -123.1394 },
      { name: 'Point Atkinson',  lat: 49.3375, lon: -123.2536 },
      { name: 'Lions Gate',      lat: 49.3154, lon: -123.1387 },
    ],
    marinePoint: { name: 'English Bay', lat: 49.28, lon: -123.20 },
    refreshMs: 10 * 60 * 1000,
    eccc: [
      { label: 'Strait of Georgia — south of Nanaimo', siteId: '14305', mapId: '02' },
      { label: 'Howe Sound',                           siteId: '14400', mapId: '02' },
    ],
    windy: { lat: 49.28, lon: -123.12, zoom: 11 },
    webcams: [],
    deepDive: [
      { label: 'WindIsGood — Island map ↗',    href: 'https://windisgood.com/island-map2.html' },
      { label: 'Windy.com full ↗',             href: 'https://www.windy.com/?49.28,-123.12,11' },
      { label: 'Weather Network — hourly ↗',   href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/vancouver' },
      { label: 'DFO tides — 07735 Vancouver ↗', href: 'https://www.tides.gc.ca/en/stations/07735' },
    ],
  } satisfies StationConfig,
  sar106: {
    slug: 'sar106',
    brand: {
      short: 'RCMSAR 106 · Shuswap',
      tagline: 'Local Lake Conditions',
      logoSrc: '/stations/sar106/logo.png',
      logoAlt: 'RCMSAR 106 Shuswap Lifeboat Society',
      faviconSrc: '/stations/sar106/favicon.png',
      accent: '#37b6ff',
      themeColor: '#0b1622',
    },
    meta: {
      title: 'RCMSAR 106 Shuswap — Local Conditions',
      description: 'RCMSAR Unit 106 Shuswap (Sicamous, Shuswap Lake) local lake conditions dashboard for wind, weather, and sky.',
      footerCredit: 'RCMSAR 106 Shuswap conditions',
    },
    labels: {
      windSub: 'Sicamous',
      seaSub: 'Shuswap Lake',
      tideSub: 'Freshwater — no tide',
      tideCardHeading: 'Tide — n/a (freshwater lake)',
      sunFootnote: 'Computed locally (SunCalc) for Sicamous.',
      forecastLocation: 'Sicamous',
      marineWarningLocation: 'Shuswap Lake',
    },
    tz: 'America/Vancouver',
    center: { name: 'Sicamous', lat: 50.8360, lon: -118.9970 },
    tideStationId: '',
    points: [
      { name: 'Sicamous',           lat: 50.8360, lon: -118.9970 },
      { name: 'Salmon Arm',         lat: 50.7010, lon: -119.2830 },
      { name: 'Cinnamousun Narrows', lat: 50.9530, lon: -119.0410 },
      { name: 'Anstey Arm',         lat: 51.0630, lon: -118.8560 },
      { name: 'Seymour Arm',        lat: 51.2400, lon: -118.9500 },
      { name: 'Blind Bay',          lat: 50.9010, lon: -119.4270 },
      { name: 'Sorrento',           lat: 50.8760, lon: -119.4640 },
    ],
    marinePoint: { name: 'Shuswap Lake', lat: 50.90, lon: -119.05 },
    refreshMs: 10 * 60 * 1000,
    eccc: [],
    windy: { lat: 50.90, lon: -119.05, zoom: 10 },
    webcams: [],
    deepDive: [
      { label: 'Windy.com full ↗',                  href: 'https://www.windy.com/?50.90,-119.05,10' },
      { label: 'Weather Network — hourly ↗',        href: 'https://www.theweathernetwork.com/ca/hourly-weather-forecast/british-columbia/sicamous' },
      { label: 'ECCC marine — Southern Interior ↗', href: 'https://weather.gc.ca/forecast/canada/index_e.html?id=BC' },
    ],
    currents: { show: false }, // freshwater lake — no BC-coast currents or tide data applies
  } satisfies StationConfig,
} as const;

export type StationSlug = keyof typeof STATIONS;
export const stationList = (): StationConfig[] => Object.values(STATIONS);
export const stationSlugs = (): StationSlug[] => Object.keys(STATIONS) as StationSlug[];
export const getStation = (slug: string): StationConfig => {
  const s = (STATIONS as Record<string, StationConfig>)[slug];
  if (!s) throw new Error(`Unknown station: ${slug}`);
  return s;
};
